[package]
name = "bleurgh"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = ">=0.5.0-rc.1"
serde = ">=1.0.0"
serde_derive = ">=1.0.0"
lazy_static = ">=0.0.1"
toml = ">=0.5.8"
